version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: d1vide/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/backend_static
      - media:/app/media

  frontend:
    image: d1vide/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: d1vide/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - backend
      - frontend
