TAG_NAME_LENGTH = 64
TAG_SLUG_LENGTH = 64
INGREDIENT_NAME_LENGTH = 64
INGREDIENT_UNIT_LENGTH = 32
RECIPE_NAME_LENGTH = 64
RECIPE_TEXT_LENGTH = 256
ERROR_ZERO_MESSAGE = "Это поле не может быть равно нулю"
