# Generated by Django 3.2.3 on 2024-06-19 11:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subscribe_unique_subscribe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('user')), _negated=True), name='check_self_subscribe'),
        ),
    ]
